#lang scheme/load
(load "prime-test.rkt")
(define (runtime) (current-milliseconds))
(define (timed-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime)))
(define (start-prime-test n star-time)
  (if (prime? n)
      (report-prime (- (runtime) start-time)) -1))
(define (report-prime elapsed-time)
  (display " *** ")
  (display elapsed-time))